//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Drawing;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace NetSparkle.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("NetSparkle.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software update error.
        /// </summary>
        internal static string DefaultNetSparkleUIFactory_ErrorTitle {
            get {
                return ResourceManager.GetString("DefaultNetSparkleUIFactory_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software update message.
        /// </summary>
        internal static string DefaultNetSparkleUIFactory_MessageTitle {
            get {
                return ResourceManager.GetString("DefaultNetSparkleUIFactory_MessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, either you aren&apos;t connected to the internet, or our server is having a problem..
        /// </summary>
        internal static string DefaultNetSparkleUIFactory_ShowCannotDownloadAppcastMessage {
            get {
                return ResourceManager.GetString("DefaultNetSparkleUIFactory_ShowCannotDownloadAppcastMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there was a problem attempting to download the update
        ///
        ///{0}.
        /// </summary>
        internal static string DefaultNetSparkleUIFactory_ShowDownloadErrorMessage {
            get {
                return ResourceManager.GetString("DefaultNetSparkleUIFactory_ShowDownloadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updater not supported, please execute {0} manually.
        /// </summary>
        internal static string DefaultNetSparkleUIFactory_ShowUnknownInstallerFormatMessageText {
            get {
                return ResourceManager.GetString("DefaultNetSparkleUIFactory_ShowUnknownInstallerFormatMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your have elected to skip this version..
        /// </summary>
        internal static string DefaultNetSparkleUIFactory_ShowVersionIsSkippedByUserRequestMessage {
            get {
                return ResourceManager.GetString("DefaultNetSparkleUIFactory_ShowVersionIsSkippedByUserRequestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current version is up to date..
        /// </summary>
        internal static string DefaultNetSparkleUIFactory_ShowVersionIsUpToDateMessage {
            get {
                return ResourceManager.GetString("DefaultNetSparkleUIFactory_ShowVersionIsUpToDateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more information.
        /// </summary>
        internal static string DefaultNetSparkleUIFactory_ToastCallToAction {
            get {
                return ResourceManager.GetString("DefaultNetSparkleUIFactory_ToastCallToAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Version Available.
        /// </summary>
        internal static string DefaultNetSparkleUIFactory_ToastMessage {
            get {
                return ResourceManager.GetString("DefaultNetSparkleUIFactory_ToastMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap software_update_available1 {
            get {
                object obj = ResourceManager.GetObject("software-update-available1", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
    }
}
